---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/institution":
    post:
      summary: Create an institution
      tags:
      - Institution
      parameters: []
      responses:
        '201':
          description: institution created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                location:
                  type: string
              required:
              - id
              - name
              - location
  "/institution/{id}":
    get:
      summary: Retrieve an institution
      tags:
      - Institution
      parameters: []
      responses:
        '200':
          description: institution found
        '404':
          description: institution not found
        '406':
          description: unsupported accept header
  "/user":
    post:
      summary: Create a User
      tags:
      - User
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                institution_id:
                  type: integer
              required:
              - id
              - first_name
              - last_name
              - email
  "/user/{id}":
    get:
      summary: Retrieve an user
      tags:
      - User
      parameters:
      - name: id
        in: path
        type: string
        schema:
          type: object
          properties:
            id:
              type: integer
            first_name:
              type: string
            last_name:
              type: string
            email:
              type: string
            institution_id:
              type: integer
          required:
          - id
          - first_name
          - last_name
          - email
          - institution_id
        required: true
      responses:
        '200':
          description: user found
        '404':
          description: user not found
        '406':
          description: unsupported accept header
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
