---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/institution":
    get:
      summary: list institutions
      tags:
      - Institution
      responses:
        '200':
          description: successful
    post:
      summary: create institution
      tags:
      - Institution
      responses:
        '200':
          description: successful
  "/api/v1/institution/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show institution
      tags:
      - Institution
      responses:
        '200':
          description: successful
    patch:
      summary: update institution
      tags:
      - Institution
      responses:
        '200':
          description: successful
    put:
      summary: update institution
      tags:
      - Institution
      responses:
        '200':
          description: successful
    delete:
      summary: delete institution
      tags:
      - Institution
      responses:
        '200':
          description: successful
  "/api/v1/user":
    get:
      summary: list users
      tags:
      - User
      responses:
        '200':
          description: successful
    post:
      summary: create user
      tags:
      - User
      responses:
        '200':
          description: successful
  "/api/v1/user/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      tags:
      - User
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      tags:
      - User
      responses:
        '200':
          description: successful
    put:
      summary: update user
      tags:
      - User
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      tags:
      - User
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
