---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/institution":
    post:
      summary: Create a institution
      tags:
      - institutions
      parameters: []
      responses:
        '201':
          description: institution created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                location:
                  type: string
              required:
              - id
              - name
              - location
  "/institutions/{id}":
    get:
      summary: Retrieve an institution
      tags:
      - institution
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: institution found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  location:
                    type: string
                required:
                - id
                - name
                - location
        '404':
          description: institution not found
        '406':
          description: unsupported accept header
  "/api/v1/user":
    post:
      summary: Create a User
      tags:
      - users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                institutions_id:
                  type: integer
              required:
              - id
              - first_name
              - last_name
              - email
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
