# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    # services:
    #   postgres:
    #     image: postgres:11-alpine
    #     ports:
    #       - "5432:5432"
    #     env:
    #       POSTGRES_DB: rails_test
    #       POSTGRES_USER: rails
    #       POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
    #   DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.133.2
        with:
          bundler: Gemfile.lock
          bundler-cache: false
      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      # Add or replace database setup steps here
      - name: Set up database schema
        run: | 
          bundle exec rails db:setup db:test:prepare
      - name: Run Test
        run: bundle exec rspec -P "spec/decorators/*.rb, spec/models/*.rb, spec/pdfs/*.rb"
      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: test-logs
          path: log/
      - name: Upload coverage results
        if: success()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: code-coverage
          path: coverage/
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3.0.1
        with:
          path: artifacts/
